language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOX_ENV=lint
    - python: 3.5
      env:
      - TOX_ENV=py34
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36
install:
  - travis_retry pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)